spring:
  application:
    name: highlights-clipper
  jmx:
    enabled: false
  http.encoding:
    charset: UTF-8
    enabled: true
    force: true
  boot:
    admin:
      client:
        enabled: false

info:
  team: Videocore
  app:
    name: ${spring.application.name}
    version: ${VERSION:unknown}
    component: Highlights Clipper

server:
  port: ${PORT:8080}

endpoints:
  autoconfig.enabled: true
  beans.enabled: true
  configprops.enabled: true
  dump.enabled: true
  env.enabled: true
  health.enabled: true
  info.enabled: true
  metrics.enabled: true
  mappings.enabled: true
  shutdown.enabled: false
  trace.enabled: true

---
spring:
  profiles: int
  boot:
    admin:
      client:
        enabled: true
        service-url: https://highlights-clipper-int.iapp.svt.se
      url: https://core-admin-int.iapp.svt.se

---
spring:
  profiles: acc
  boot:
    admin:
      client:
        enabled: true
        service-url: https://highlights-clipper-acc.iapp.svt.se
      url: https://core-admin-acc.iapp.svt.se

---
spring:
  profiles: prod
  boot:
    admin:
      client:
        enabled: true
        service-url: https://highlights-clipper.iapp.svt.se
      url: https://core-admin.iapp.svt.se