spring:
  jpa:
    database: POSTGRESQL
    show-sql: false
    hibernate:
      ddl-auto: create
      format_sql: true
      cache:
        queries: false
        use_second_level_cache: false
        use_query_cache: false
        region:
          factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:cua;IGNORECASE=TRUE;MODE=PostgreSQL;INIT=CREATE SCHEMA IF NOT EXISTS "public";DB_CLOSE_DELAY=-1;
    username: sa
    password: 
  jackson:
    serialization:
        WRITE_DATES_AS_TIMESTAMPS: false      
  tomcat:
    test-on-borrow: true
    test-while-idle: true
    validation-query: SELECT 1;
    max-idle: 35
    min-idle: 10
    time-between-eviction-runs-millis: 3000
    initial-size: 10
  http.encoding:
    charset: UTF-8
    enabled: true
    force: true
  h2:
    console.enabled: true
    console.path: /h2-console
    
endpoints:
  enabled: true
  ##No auth protected
  shutdown.sensitive: false
  ##Enable shutdown endpoint
  shutdown.enabled: true
  
security:
  user:
    name: user
    password: password
    
mail:
    host: smtp.gmail.com
    port: 587
    username: pepe@gmail.com
    password: <login_password_to_smtp_server>
    properties:
        mail.smtp:
                auth: true
                starttls.enable: true