spring:
  jpa:
    database: POSTGRESQL
    show-sql: false
    hibernate:
      ddl-auto: create
      format_sql: true
      cache:
        queries: false
        use_second_level_cache: false
        use_query_cache: false
        region:
          factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
  datasource:
    ## PostgreSQL
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.0.27:5432/cua_admin.dev
    username: admin
    password: admin
  jackson:
    serialization:
        WRITE_DATES_AS_TIMESTAMPS: false      
  tomcat:
    test-on-borrow: true
    test-while-idle: true
    validation-query: SELECT 1;
    max-idle: 35
    min-idle: 10
    time-between-eviction-runs-millis: 3000
    initial-size: 10
  http.encoding:
    charset: UTF-8
    enabled: true
    force: true
  h2:
    console.enabled: true
    console.path: /h2-console
    
endpoints:
  enabled: true
  ##No auth protected
  shutdown.sensitive: false
  ##Enable shutdown endpoint
  shutdown.enabled: true

security:
  user:
    name: user
    password: password
