## YAML Template.
##jdbc:h2:mem:cua;IGNORECASE=TRUE;MODE=PostgreSQL;INIT=CREATE SCHEMA IF NOT EXISTS "public";DB_CLOSE_DELAY=-1;
##jdbc:postgresql://192.168.0.28:5432/cua_admin.dev
##org.postgresql.Driver
##

spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
        ddl-auto: create
        default_schema: nextg
        format_sql: true
        ##id.new_generator_mappings: true
        cache:
            queries: false
            use_second_level_cache: false
            use_query_cache: false
            region:
                ##factory_class: 'org.hibernate.cache.ehcache.EhCacheRegionFactory'
                factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
  ##datasource:
    ## PostgreSQL
    ##driver-class-name: org.postgresql.Driver
    ##url: jdbc:postgresql://192.168.0.27:5432/cua_admin.dev
    ##username: admin
    ##password: admin
    ## H2
    ##driver-class-name: org.h2.Driver
    ##url: jdbc:h2:mem:cua;DB_CLOSE_ON_EXIT=TRUE;IGNORECASE=TRUE;MODE=PostgreSQL;INIT=CREATE SCHEMA IF NOT EXISTS nextg;DB_CLOSE_DELAY=-1;
    ##username: sa
    ##password: 
    tomcat:
        test-on-borrow: true
        test-while-idle: true
        validation-query: SELECT 1;
        max-idle: 35
        min-idle: 10
        time-between-eviction-runs-millis: 3000
        initial-size: 10
    http.encoding:
        charset: UTF-8
        enabled: true
        force: true
    h2:
        console.enabled: true
        console.path: /h2-console
endpoints:
    enabled: true
    ##No auth  protected 
    shutdown.sensitive: false
    ##Enable shutdown endpoint
    shutdown.enabled: true

---
spring:
  profiles: default
  datasource:
        ## PostgreSQL
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.0.27:5432/cua_admin.dev
    username: admin
    password: admin

---
spring:
  profiles: qas
  datasource:
        ## PostgreSQL
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.0.27:5432/cua_admin.qas
    username: admin
    password: admin

---
spring:
  profiles: prd
  datasource:
        ## PostgreSQL
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.0.27:5432/cua_admin.prd
    username: admin
    password: admin